### ISSUE TITLE
Debugging Pypi

### ISSUE THREAD

**Issue by Erotemic** [GERSL/pycold#11]
@SuYe99 Looks like the publishing to test pypi failed. Can you add me as a collaborator to this repo so I have permission to push branches to it directly? That will let me debug the issue quicker.

**Comment by SuYe99** [comment]
@Erotemic Hi Jon, I have added you into the Admin. Let me know what else you need from my side.

**Comment by Erotemic** [comment]
Looks like everything is working. The package upload to test pypi was successful: https://test.pypi.org/project/pycold/0.1.0/

Given that I have admin powers, I took the liberty of also making the first release (mainly to ensure nobody else takes the name pycold).

The release procedure I typically follow is: 

* Use the "new release" button on the repo webpage to draft a new release. 
* Specify a tag that corresponds with the current version prefixed with a "v" to indicate it is a version tag
* Paste the contents of the CHANGELOG for this version in the release notes.

So in this instance, I made the tag "v0.1.0", and you can see that it triggered a CI job: https://github.com/GERSL/pycold/actions/runs/3024343694 where it performs the "Upload to Live Pypi" action instead of test.

This worked an pycold is now live on pypi: https://pypi.org/project/pycold/0.1.0/

After a release I generally do a post-release procedure where I:

* Update the version in `__init__.py` by bumping the patch version. (If I decide I want to bump a major or minor version, I amend that later) 
* Marking the previous version as released in the CHANGELOG.md and starting a new section for the new version (keeping a changelog isn't the most important thing in the world, but I find it is good practice, and it helps with release notes).

I performed this on the devel branch 
Now that there is a released version on pypi, I also updated the devel branch with new pypi badges.
