### ISSUE TITLE
multiple types as pycold inputs

### ISSUE THREAD

**Issue by SuYe99** [GERSL/pycold#22]
The current pycold package only supports the array inputs as 'np.int64' such as [pycold.cold_detect](https://github.com/GERSL/pycold/blob/7c11a7d2ec59d2ce2cb628da3664d6964042a99a/src/python/pycold/_pycold_cython.pyx#L156). This is mainly because that it has the best fit into the C functions which only accepts 'long' as inputted vector type, and we don't need to do extra conversion in the cython codes. We may consider adding a support for multiple input types which frees users from 'type cast' for their input (e.g., .astype(np.int64)). For the cython part, it looks easy to use 'fused types'. But I don't know how to create a 'template' function for C and linking it to cython functions. @Erotemic You may have suggestion for this?

**Comment by Erotemic** [comment]
C doesn't have templates. I think you have to basically make copies of the function with different types. I'm not a C expert though. However, I think you can write a templated C++ component and still call it from Cython. Again, not exactly sure how to do it. 

Looks like the google results for "templates cython" have possible solutions if you are willing to write some C++.

**Comment by SuYe99** [comment]
Fixed it using a python wrapper solution
